/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imagenes;

/**
 *
 * @author akbal
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    private String calcularnombre(){
    String resultado = "G-";
    resultado= resultado + (chkcabello.isSelected() ? "C" : "0");
    resultado= resultado + (chkdientes.isSelected() ? "D" : "0");
    resultado= resultado + (chklentes.isSelected() ? "L" : "0");
    resultado= resultado + (chkbarbilla.isSelected() ? "B" : "0");
    return resultado+".jpeg";
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        chkbarbilla = new javax.swing.JCheckBox();
        chklentes = new javax.swing.JCheckBox();
        chkcabello = new javax.swing.JCheckBox();
        chkdientes = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/G-0000.jpeg"))); // NOI18N

        chkbarbilla.setText("Barbilla");
        chkbarbilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkbarbillaActionPerformed(evt);
            }
        });

        chklentes.setText("Lentes");
        chklentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chklentesActionPerformed(evt);
            }
        });

        chkcabello.setText("Pelo");
        chkcabello.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkcabelloActionPerformed(evt);
            }
        });

        chkdientes.setText("Dientes");
        chkdientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkdientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkcabello)
                    .addComponent(chkdientes)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chklentes)
                        .addGap(75, 75, 75)
                        .addComponent(jLabel1))
                    .addComponent(chkbarbilla))
                .addGap(86, 135, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(chkbarbilla)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chklentes)
                        .addGap(18, 18, 18)
                        .addComponent(chkcabello))
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(chkdientes)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkbarbillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkbarbillaActionPerformed
jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(String.format("/IMAGES/%s",calcularnombre()))));
 // TODO add your handling code here:
    }//GEN-LAST:event_chkbarbillaActionPerformed

    private void chklentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chklentesActionPerformed
  jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(String.format("/IMAGES/%s",calcularnombre()))));  // TODO add your handling code here:
    }//GEN-LAST:event_chklentesActionPerformed

    private void chkcabelloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkcabelloActionPerformed
jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(String.format("/IMAGES/%s",calcularnombre()))));        // TODO add your handling code here:
    }//GEN-LAST:event_chkcabelloActionPerformed

    private void chkdientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkdientesActionPerformed
jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(String.format("/IMAGES/%s",calcularnombre()))));      // TODO add your handling code here:
    }//GEN-LAST:event_chkdientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkbarbilla;
    private javax.swing.JCheckBox chkcabello;
    private javax.swing.JCheckBox chkdientes;
    private javax.swing.JCheckBox chklentes;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
